"""Bundled scanner definitions that can be enabled per project."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class BundledScanner:
    name: str
    description: str
    command: str
    args: tuple[str, ...]
    file_types: tuple[str, ...]

    def toml(self) -> str:
        rendered_args = ", ".join(f'"{arg}"' for arg in self.args)
        rendered_file_types = ", ".join(f'"{file_type}"' for file_type in self.file_types)
        return (
            f"# Generated by 'filigree scanner enable {self.name}'.\n"
            f"# Edit freely; 'filigree scanner disable {self.name}' will require --force if this bundled-name config is modified.\n"
            "[scanner]\n"
            f'name = "{self.name}"\n'
            f'description = "{self.description}"\n'
            f'command = "{self.command}"\n'
            f"args = [{rendered_args}]\n"
            f"file_types = [{rendered_file_types}]\n"
        )


BUNDLED_SCANNERS: dict[str, BundledScanner] = {
    "codex": BundledScanner(
        name="codex",
        description="Per-file bug hunt using Codex CLI",
        command="filigree-scanner-codex",
        args=(
            "--root",
            "{project_root}",
            "--file",
            "{file}",
            "--max-files",
            "1",
            "--api-url",
            "{api_url}",
            "--scan-run-id",
            "{scan_run_id}",
            "--prompt",
            "{prompt}",
        ),
        file_types=("py",),
    ),
    "claude": BundledScanner(
        name="claude",
        description="Per-file bug hunt using Claude CLI",
        command="filigree-scanner-claude",
        args=(
            "--root",
            "{project_root}",
            "--file",
            "{file}",
            "--max-files",
            "1",
            "--api-url",
            "{api_url}",
            "--scan-run-id",
            "{scan_run_id}",
            "--prompt",
            "{prompt}",
        ),
        file_types=("py",),
    ),
}


def get_bundled_scanner(name: str) -> BundledScanner | None:
    return BUNDLED_SCANNERS.get(name)
