"""Bundled scanner definitions that can be enabled per project."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Literal

from filigree.scanners import load_scanner

BundledScannerStatus = Literal["missing", "current", "stale_bundled", "custom"]


@dataclass(frozen=True)
class BundledScanner:
    name: str
    description: str
    command: str
    args: tuple[str, ...]
    file_types: tuple[str, ...]
    language_focus: tuple[str, ...]

    def toml(self) -> str:
        rendered_args = ", ".join(f'"{arg}"' for arg in self.args)
        rendered_file_types = ", ".join(f'"{file_type}"' for file_type in self.file_types)
        return (
            f"# Generated by 'filigree scanner enable {self.name}'.\n"
            f"# Edit freely; 'filigree scanner disable {self.name}' will require --force if this bundled-name config is modified.\n"
            "[scanner]\n"
            f'name = "{self.name}"\n'
            f'description = "{self.description}"\n'
            f'command = "{self.command}"\n'
            f"args = [{rendered_args}]\n"
            f"file_types = [{rendered_file_types}]\n"
        )


BUNDLED_SCANNERS: dict[str, BundledScanner] = {
    "codex": BundledScanner(
        name="codex",
        description="Per-file bug hunt using Codex CLI",
        command="filigree-scanner-codex",
        args=(
            "--root",
            "{project_root}",
            "--file",
            "{file}",
            "--max-files",
            "1",
            "--api-url",
            "{api_url}",
            "--api-token-env",
            "FILIGREE_FEDERATION_API_TOKEN",
            "--scan-run-id",
            "{scan_run_id}",
            "--prompt",
            "{prompt}",
        ),
        file_types=("py",),
        language_focus=("python",),
    ),
    "claude": BundledScanner(
        name="claude",
        description="Per-file bug hunt using Claude CLI",
        command="filigree-scanner-claude",
        args=(
            "--root",
            "{project_root}",
            "--file",
            "{file}",
            "--max-files",
            "1",
            "--api-url",
            "{api_url}",
            "--api-token-env",
            "FILIGREE_FEDERATION_API_TOKEN",
            "--scan-run-id",
            "{scan_run_id}",
            "--prompt",
            "{prompt}",
        ),
        file_types=("py",),
        language_focus=("python",),
    ),
}


def get_bundled_scanner(name: str) -> BundledScanner | None:
    return BUNDLED_SCANNERS.get(name)


def bundled_scanner_config_status(scanners_dir: Path, scanner_name: str) -> BundledScannerStatus:
    """Classify a project scanner registration against a bundled definition."""
    bundled = get_bundled_scanner(scanner_name)
    if bundled is None:
        return "missing"
    path = scanners_dir / f"{scanner_name}.toml"
    if not path.is_file():
        return "missing"
    cfg = load_scanner(scanners_dir, scanner_name)
    if cfg is None or cfg.command != bundled.command:
        return "custom"
    if cfg.args == bundled.args and cfg.file_types == bundled.file_types:
        return "current"
    return "stale_bundled"


def bundled_scanner_matches(scanners_dir: Path, scanner_name: str) -> bool:
    """Return whether a project registration exactly matches the bundled scanner."""
    return bundled_scanner_config_status(scanners_dir, scanner_name) == "current"


def looks_like_stale_bundled_scanner(scanners_dir: Path, scanner_name: str) -> bool:
    """Return whether a registration appears to be an older bundled scanner."""
    return bundled_scanner_config_status(scanners_dir, scanner_name) == "stale_bundled"
